index:
    path: /
    controller: App\limabundle\LimaBundle\Controller\LimaController::index

basesettables:
    path: /basesettables
    controller: App\limabundle\LimaBundle\Controller\LimaController::basesettables

genereruncrud:
    path: /genereruncrud
    controller: App\limabundle\LimaBundle\Controller\LimaController::genereruncrud

supprimeruncrud:
    path: /supprimeruncrud
    controller: App\limabundle\LimaBundle\Controller\LimaController::supprimeruncrud

genererunerelation:
    path: /genererunerelation
    controller: App\limabundle\LimaBundle\Controller\LimaController::genererunerelation

authsecurite:
    path: /authsecurite
    controller: App\limabundle\LimaBundle\Controller\LimaController::authsecurite

console:
    path: /console
    controller: App\limabundle\LimaBundle\Controller\LimaController::console

swiftmailer:
    path: /swiftmailer
    controller: App\limabundle\LimaBundle\Controller\LimaController::swiftmailer
